In [153]:
import galois
import numpy as np

In [154]:
from cnc_tableau import CncSimulator as cnc
import cnc_tableau as cnc_tableau

In [155]:
# Define the field GF(2), which is F2
GF2 = galois.GF(2)

In [156]:
#v, residuals, rank, s = np.linalg.lstsq(E, e, rcond=None)

In [157]:
# trial CNC set:
n = 4; m =3; d = n-m; N = n+m+1; xi = 2*m+1

In [158]:
tab = cnc(n,m)

In [159]:
tab._table

array([[0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 0]])

In [160]:
(tab._mat @ tab._J @ np.transpose(tab._mat))%2

array([[0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 0]])

In [161]:
cnc_tableau.symplectic_inner_product(tab._mat[3,:],tab._mat[7,:])

1

In [162]:
#S = ['h_2','cnot_1_2','cnot_1_3']
#cnc.apply_sequence_of_clifford(tab,S)

In [163]:
#S = ['cnot_1_2','cnot_1_3','cnot_1_4']
#cnc.apply_sequence_of_clifford(tab,S)

In [164]:
#S = ['h_1','h_2','h_4','cnot_1_2','cnot_2_3','cnot_3_4']
#cnc.apply_sequence_of_clifford(tab,S)

In [165]:
tab._table

array([[0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 0]])

In [166]:
np.array([0, 1, 1, 0, 0, 1, 0, 0])^np.array([0, 1, 1, 0, 0, 1, 1, 1])

array([0, 0, 0, 0, 0, 0, 1, 1])

In [167]:
cnc.is_cnc_(tab)

True

In [168]:
#b = GF2([1,1,1,1,1,0])
b = np.array([1 for i in range(n)]+[0 for i in range(n)]); b[0]=0

In [169]:
cnc.measure(tab,b)

Pauli is in normalizer of stabilizer but not in any coset.


1

In [170]:
tab._table

array([[0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1]])

In [171]:
cnc.is_cnc_(tab)

True