In [82]:
import numpy as np
from src import tableau_helper_functions as helper
from src import updated_cnc_tableau as cnc

In [83]:
data1 = np.load("./keys/cnc_tableau_keys_4.npy",allow_pickle=True)
data2 = np.load("./keys/stab_tableau_keys_4.npy",allow_pickle=True)

In [86]:
# first tableau:
tableau1 = data1[0][1]
n1 = data1[0][2]
m1 = data1[0][3]

# second tableau:
tableau2 = data2[0][1]
n2 = data2[0][2]
m2 = data2[0][3]

In [87]:
m2

0

In [88]:
tableau1

array([[1, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 1, 0, 0]], dtype=object)

In [101]:
tableau2

array([[0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 0, 0, 1]], dtype=object)

In [112]:
cnc.CncSimulator.from_tableau(4,0,np.concatenate((tableau2,np.zeros((1,tableau2.shape[1]),dtype=np.int64)),axis=0))

CNC Simulator with n=4, m=0
Destabilizers: <IIZI, IZII, IIIX, XIII>
Stabilizers: <IIXI, IXII, -XIIY, -YIIX>
JW Elements: IIII

In [115]:
T = np.array([1,1/np.sqrt(2),1/np.sqrt(2),0])

In [120]:
np.all(T == T)

True

In [90]:
tableau22 = helper.compose_tableaus(tableau2,tableau2,m2,m2)

In [113]:
cnc.CncSimulator.from_tableau(8,0,np.concatenate((tableau22,np.zeros((1,tableau22.shape[1]),dtype=np.int64)),axis=0))

CNC Simulator with n=8, m=0
Destabilizers: <IIIIIIZI, IIIIIZII, IIIIIIIX, IIIIXIII, IIZIIIII, IZIIIIII, IIIXIIII, XIIIIIII>
Stabilizers: <IIIIIIXI, IIIIIXII, -IIIIXIIY, -IIIIYIIX, IIXIIIII, IXIIIIII, -XIIYIIII, -YIIXIIII>
JW Elements: IIIIIIII

In [8]:
tableau21 = helper.compose_tableaus(tableau2,tableau1,m2,m1)

In [10]:
# check for input cnc:
cnc_tableau = cnc.CncSimulator.from_tableau(n1,m1,tableau1)
cnc_tableau.is_cnc(n1,m1,tableau1)

True

In [11]:
# check for input cnc tensored with stab:
cnc_tableau = cnc.CncSimulator.from_tableau(n1+n2,m1,tableau21)
cnc_tableau.is_cnc(n1+n2,m1,tableau21)

True

In [12]:
tableau12 = helper.compose_tableaus(tableau1,tableau2,m1,m2)

In [14]:
tableau12

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,

In [13]:
# check for input cnc tensored with stab:
cnc_tableau = cnc.CncSimulator.from_tableau(n1+n2,m1,tableau21)
cnc_tableau.is_cnc(n1+n2,m1,tableau21)

True

In [15]:
cnc_tableaus = np.load("./keys/cnc_tableau_keys_4.npy",allow_pickle=True)
stab_tableaus = np.load("./keys/stab_tableau_keys_4.npy",allow_pickle=True)

In [34]:
data = np.load("./keys/keys_n_5.npy",allow_pickle=True)

In [80]:
n = 1
data = np.load(f"./keys/stab_tableau_keys_{n}.npy",allow_pickle=True)

In [81]:
for i in range(len(data)):
    zeros = np.zeros((1,data[i][1].shape[1]),np.int64)
    tableau = np.concatenate((data[i][1],zeros),axis = 0)

    print(f"Quasiprobaiblity weight: {data[i][0]}")
    print(f"Tableau:\n{tableau}","\n")
    print(f"CNC object:\n{cnc.CncSimulator(data[i][2],data[i][3],tableau)}","\n")

Quasiprobaiblity weight: -0.20710678118654746
Tableau:
[[1 0 0]
 [1 1 1]
 [0 0 0]] 

CNC object:
CNC Simulator with n=1, m=0
Destabilizers: <Z>
Stabilizers: <X>
JW Elements: I 

Quasiprobaiblity weight: 0.7071067811865475
Tableau:
[[0 1 0]
 [1 0 0]
 [0 0 0]] 

CNC object:
CNC Simulator with n=1, m=0
Destabilizers: <Z>
Stabilizers: <X>
JW Elements: I 

Quasiprobaiblity weight: 0.5
Tableau:
[[1 0 0]
 [1 1 0]
 [0 0 0]] 

CNC object:
CNC Simulator with n=1, m=0
Destabilizers: <Z>
Stabilizers: <X>
JW Elements: I 



In [26]:
filename = "./keys/all_stab_keys_4.h5"
n = 2

with h5py.File(filename, "r") as f:
        key = f"n={n}"
        data = np.array(list(f[key]))